src/Entity/Import.php
<?php

namespace App\Entity;

use App\Repository\ImportRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ImportRepository::class)
 */
class Import
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=60, nullable=false)
     */
    private $compte_affaire;

    /**
     * @ORM\Column(type="string", length=60, nullable=true)
     */
    private $compte_evenement;

    /**
     * @ORM\Column(type="string", length=70, nullable=true)
     */
    private $compte_dernier_event;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $numero_fiche;

    /**
     * @ORM\Column(type="string", length=9, nullable=true)
     */
    private $libelle_civilite;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $propriete_vehicule;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=70, nullable=true)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $num_nom_voie;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $complement_adresse;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="string", length=40, nullable=true)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $telephone_domicile;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $telephone_portable;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $telephone_job;

    /**
     * @ORM\Column(type="string", length=60, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_mise_en_circulation;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_achat;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_dernier_event;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $libelle_marque;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $libelle_modele;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $version;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $vin;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $immatriculation;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $type_prospect;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $kilometrage;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $libelle_energie;

    /**
     * @ORM\Column(type="string", length=60, nullable=true)
     */
    private $vendeur_vn;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $vendeur_vo;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $commentaire_facturation;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $type_vn_vo;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $num_dossier_vn_vo;

    /**
     * @ORM\Column(type="string", length=70, nullable=true)
     */
    private $intermediaire_vente;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_evenement_veh;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $originine_evenement;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCompteAffaire(): ?string
    {
        return $this->compte_affaire;
    }

    public function setCompteAffaire(string $compte_affaire): self
    {
        $this->compte_affaire = $compte_affaire;

        return $this;
    }

    public function getCompteEvenement(): ?string
    {
        return $this->compte_evenement;
    }

    public function setCompteEvenement(?string $compte_evenement): self
    {
        $this->compte_evenement = $compte_evenement;

        return $this;
    }

    public function getCompteDernierEvent(): ?string
    {
        return $this->compte_dernier_event;
    }

    public function setCompteDernierEvent(?string $compte_dernier_event): self
    {
        $this->compte_dernier_event = $compte_dernier_event;

        return $this;
    }

    public function getNumeroFiche(): ?int
    {
        return $this->numero_fiche;
    }

    public function setNumeroFiche(?int $numero_fiche): self
    {
        $this->numero_fiche = $numero_fiche;

        return $this;
    }

    public function getLibelleCivilite(): ?string
    {
        return $this->libelle_civilite;
    }

    public function setLibelleCivilite(?string $libelle_civilite): self
    {
        $this->libelle_civilite = $libelle_civilite;

        return $this;
    }

    public function getProprieteVehicule(): ?string
    {
        return $this->propriete_vehicule;
    }

    public function setProprieteVehicule(?string $propriete_vehicule): self
    {
        $this->propriete_vehicule = $propriete_vehicule;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNumNomVoie(): ?string
    {
        return $this->num_nom_voie;
    }

    public function setNumNomVoie(?string $num_nom_voie): self
    {
        $this->num_nom_voie = $num_nom_voie;

        return $this;
    }

    public function getComplementAdresse(): ?string
    {
        return $this->complement_adresse;
    }

    public function setComplementAdresse(?string $complement_adresse): self
    {
        $this->complement_adresse = $complement_adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(?string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getTelephoneDomicile(): ?string
    {
        return $this->telephone_domicile;
    }

    public function setTelephoneDomicile(?string $telephone_domicile): self
    {
        $this->telephone_domicile = $telephone_domicile;

        return $this;
    }

    public function getTelephonePortable(): ?string
    {
        return $this->telephone_portable;
    }

    public function setTelephonePortable(?string $telephone_portable): self
    {
        $this->telephone_portable = $telephone_portable;

        return $this;
    }

    public function getTelephoneJob(): ?string
    {
        return $this->telephone_job;
    }

    public function setTelephoneJob(?string $telephone_job): self
    {
        $this->telephone_job = $telephone_job;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getDateMiseEnCirculation(): ?\DateTimeInterface
    {
        return $this->date_mise_en_circulation;
    }

    public function setDateMiseEnCirculation(?\DateTimeInterface $date_mise_en_circulation): self
    {
        $this->date_mise_en_circulation = $date_mise_en_circulation;

        return $this;
    }

    public function getDateAchat(): ?\DateTimeInterface
    {
        return $this->date_achat;
    }

    public function setDateAchat(?\DateTimeInterface $date_achat): self
    {
        $this->date_achat = $date_achat;

        return $this;
    }

    public function getDateDernierEvent(): ?\DateTimeInterface
    {
        return $this->date_dernier_event;
    }

    public function setDateDernierEvent(?\DateTimeInterface $date_dernier_event): self
    {
        $this->date_dernier_event = $date_dernier_event;

        return $this;
    }

    public function getLibelleMarque(): ?string
    {
        return $this->libelle_marque;
    }

    public function setLibelleMarque(?string $libelle_marque): self
    {
        $this->libelle_marque = $libelle_marque;

        return $this;
    }

    public function getLibelleModele(): ?string
    {
        return $this->libelle_modele;
    }

    public function setLibelleModele(?string $libelle_modele): self
    {
        $this->libelle_modele = $libelle_modele;

        return $this;
    }

    public function getVersion(): ?string
    {
        return $this->version;
    }

    public function setVersion(?string $version): self
    {
        $this->version = $version;

        return $this;
    }

    public function getVin(): ?string
    {
        return $this->vin;
    }

    public function setVin(?string $vin): self
    {
        $this->vin = $vin;

        return $this;
    }

    public function getImmatriculation(): ?string
    {
        return $this->immatriculation;
    }

    public function setImmatriculation(?string $immatriculation): self
    {
        $this->immatriculation = $immatriculation;

        return $this;
    }

src/Form/ImportType.php
<?php

namespace App\Form;

use App\Entity\Import;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Validator\Constraints\NotBlank;

class ImportType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('compte_affaire', null, [
                'constraints' => [
                    new NotBlank([
                        'message' => 'Veuillez fournir une valeur pour le champ Compte affaire',
                    ]),
                ],
            ])
            ->add('compte_evenement')
            ->add('compte_dernier_event')
            ->add('numero_fiche')
            ->add('libelle_civilite')
            ->add('propriete_vehicule')
            ->add('nom')
            ->add('prenom')
            ->add('num_nom_voie')
            ->add('complement_adresse')
            ->add('code_postal')
            ->add('ville')
            ->add('telephone_domicile')
            ->add('telephone_portable')
            ->add('telephone_job')
            ->add('email')
            ->add('date_mise_en_circulation', DateType::class, [
                'widget' => 'single_text',
                'input' => 'datetime',
            ])
            ->add('date_achat', DateType::class, [
                'widget' => 'single_text',
                'input' => 'datetime',
            ])
            ->add('date_dernier_event', DateType::class, [
                'widget' => 'single_text',
                'input' => 'datetime',
            ])
            ->add('libelle_marque')
            ->add('libelle_modele')
            ->add('version')
            ->add('vin')
            ->add('immatriculation')
            ->add('type_prospect')
            ->add('kilometrage')
            ->add('libelle_energie')
            ->add('vendeur_vn')
            ->add('vendeur_vo')
            ->add('commentaire_facturation')
            ->add('type_vn_vo')
            ->add('num_dossier_vn_vo')
            ->add('intermediaire_vente')
            ->add('date_evenement_veh', DateType::class, [
                'widget' => 'single_text',
                'input' => 'datetime',
            ])
            ->add('originine_evenement');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Import::class,
        ]);
    }
}

src/Controller/ImportController.php
<?php

namespace App\Controller;

use App\Entity\Import;
use App\Form\ImportType;
use App\Repository\ImportRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ImportController extends AbstractController
{
    private $importRepository;

    public function __construct(ImportRepository $importRepository)
    {
        $this->importRepository = $importRepository;
    }

    /**
     * @Route("/", name="app_import_list", methods={"GET"})
     */
    public function list(): Response
    {
        $imports = $this->importRepository->findAll();

        return $this->render('import/list.html.twig', [
            'imports' => $imports,
        ]);
    }

    /**
     * @Route("/new", name="app_import_new", methods={"GET", "POST"})
     */
    public function new(Request $request): Response
    {
        $import = new Import();
        $form = $this->createForm(ImportType::class, $import);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->importRepository->add($import, true);

            return $this->redirectToRoute('app_import_list');
        }

        return $this->render('import/new.html.twig', [
            'import' => $import,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_import_show", methods={"GET"})
     */
    public function show(Import $import): Response
    {
        return $this->render('import/show.html.twig', [
            'import' => $import,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_import_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Import $import): Response
    {
        $form = $this->createForm(ImportType::class, $import);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->importRepository->add($import, true);

            return $this->redirectToRoute('app_import_list');
        }

        return $this->render('import/edit.html.twig', [
            'import' => $import,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_import_delete", methods={"POST"})
     */
    public function delete(Request $request, Import $import): Response
    {
        if ($this->isCsrfTokenValid('delete' . $import->getId(), $request->request->get('_token'))) {
            $this->importRepository->remove($import, true);
        }

        return $this->redirectToRoute('app_import_list');
    }
}

templates/Import/_delete_form.html.twig
<form method="post" action="{{ path('app_import_delete', {'id': import.id}) }}" onsubmit="return confirm('Êtes-vous sûr de bien vouloir supprimer cet élément?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ import.id) }}">
	<button class="btn btn-sm btn-outline-danger">Supprimer</button>
</form>

templates/Import/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit élément
{% endblock %}

{% block body %}
	<h1 class="mb-3">Edit élément</h1>

	<div class="btn-group mb-3" role="group" aria-label="Actions">
		<a href="{{ path('app_import_list') }}" class="btn btn-sm btn-outline-secondary">Annuler</a>
		&nbsp;
		{{ include('import/_delete_form.html.twig') }}
	</div>

	{{ include('import/_form.html.twig', {'button_label': 'Enregistrer'}) }}
{% endblock %}

templates/Import/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="container-fluid table-container">
		<h1 class=" mt-3 mb-3">Liste des données :</h1>

		{% if imports is defined and imports is not empty %}
			<table id="product-table" class="table table-hover">
				<thead>
					<tr>
						<th></th>
						<th>Compte Affaire</th>
						<th>Compte évènement (Veh)</th>
						<th>Compte dernier évènement (Veh)</th>
						<th>Numéro de fiche</th>
						<th>Libellé civilité</th>
						<th>Propriétaire actuel du véhicule</th>
						<th>Nom</th>
						<th>Prénom</th>
						<th>N° et Nom de la voie</th>
						<th>Complément adresse 1</th>
						<th>Code postal</th>
						<th>Ville</th>
						<th>Téléphone domicile</th>
						<th>Téléphone portable</th>
						<th>Téléphone job</th>
						<th>Email</th>
						<th>Date de mise en circulation</th>
						<th>Date achat</th>
						<th>Date dernier évènement (Veh)</th>
						<th>Libellé marque (Mrq)</th>
						<th>Libellé modèle (Mod)</th>
						<th>Version</th>
						<th>VIN</th>
						<th>Immatriculation</th>
						<th>Type de prospect</th>
						<th>Kilométrage</th>
						<th>Libellé énergie (Energ)</th>
						<th>Vendeur VN</th>
						<th>Vendeur VO</th>
						<th>Commentaire de facturation (Veh)</th>
						<th>Type VN VO</th>
						<th>Numéro de dossier VN VO</th>
						<th>Intermediaire de vente VN</th>
						<th>Date évènement (Veh)</th>
						<th>Origine évènement (Veh)</th>
					</tr>
				</thead>
				<tbody>
					{% for imp in imports %}
						<tr>
							<td class="no-wrap">
								<div class="btn-group" role="group" aria-label="Actions">
									<a href="{{ path('app_import_show', {'id': imp.id}) }}" class="btn btn-sm btn-outline-primary">Modifier</a>
									<a href="{{ path('app_import_edit', {'id': imp.id}) }}" class="btn btn-sm btn-outline-danger">Supprimer</a>
								</div>
							</td>
							<td>{{ imp.compteAffaire }}</td>
							<td>{{ imp.compteEvenement }}</td>
							<td>{{ imp.compteDernierEvent }}</td>
							<td>{{ imp.numeroFiche }}</td>
							<td>{{ imp.libelleCivilite }}</td>
							<td>{{ imp.proprieteVehicule }}</td>
							<td>{{ imp.nom }}</td>
							<td>{{ imp.prenom }}</td>
							<td>{{ imp.numNomVoie }}</td>
							<td>{{ imp.complementAdresse }}</td>
							<td>{{ imp.codePostal }}</td>
							<td>{{ imp.ville }}</td>
							<td>{{ imp.telephoneDomicile }}</td>
							<td>{{ imp.telephonePortable }}</td>
							<td>{{ imp.telephoneJob }}</td>
							<td>{{ imp.email }}</td>
							<td>{{ imp.dateMiseEnCirculation ? imp.dateMiseEnCirculation|date('Y-m-d') : '' }}</td>
							<td>{{ imp.dateAchat ? imp.dateAchat|date('d/m/Y') :'' }}</td>
							<td>{{ imp.dateDernierEvent ? imp.dateDernierEvent|date('d/m/Y'):'' }}</td>
							<td>{{ imp.libelleMarque }}</td>
							<td>{{ imp.libelleModele }}</td>
							<td>{{ imp.version }}</td>
							<td>{{ imp.vin }}</td>
							<td>{{ imp.immatriculation }}</td>
							<td>{{ imp.typeProspect }}</td>
							<td>{{ imp.kilometrage }}</td>
							<td>{{ imp.libelleEnergie }}</td>
							<td>{{ imp.vendeurVn }}</td>
							<td>{{ imp.vendeurVo }}</td>
							<td>{{ imp.commentaireFacturation }}</td>
							<td>{{ imp.typeVnVo }}</td>
							<td>{{ imp.numDossierVnVo }}</td>
							<td>{{ imp.intermediaireVente }}</td>
							<td>{{ imp.dateEvenementVeh ? imp.dateEvenementVeh|date('d/m/Y') : '' }}</td>
							<td>{{ imp.originineEvenement }}</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	{% else %}
		<div class="alert alert-info">
			Aucune donnée n'est disponible pour affichage.
		</div>
	{% endif %}
{% endblock %}

templates/Import/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau donnée
{% endblock %}

{% block body %}
	<h1 class="mb-3">Créer nouveau élément</h1>
	<div class="btn-group mb-3" role="group" aria-label="Actions">
		<a href="{{ path('app_import_list') }}" class="btn btn-sm btn-outline-secondary mt-2">Annuler</a>
	</div>
	{{ include('import/_form.html.twig') }}
{% endblock %}

templates/Import/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Elément
{% endblock %}

{% block body %}
	<h1>Détails de donnée</h1>

	<div class="btn-group" role="group" aria-label="Actions">
		<a href="{{ path('app_import_list') }}" class="btn btn-sm btn-outline-secondary">Annuler</a>
		&nbsp;
		<a href="{{ path('app_import_edit', {'id': import.id}) }}" class="btn btn-sm btn-outline-primary">Editer</a>
		&nbsp;
		{{ include('import/_delete_form.html.twig') }}
	</div>

	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ import.id }}</td>
			</tr>
			<tr>
				<th>Compte_affaire</th>
				<td>{{ import.compteAffaire }}</td>
			</tr>
			<tr>
				<th>Compte_evenement</th>
				<td>{{ import.compteEvenement }}</td>
			</tr>
			<tr>
				<th>Compte_dernier_event</th>
				<td>{{ import.compteDernierEvent }}</td>
			</tr>
			<tr>
				<th>Numero_fiche</th>
				<td>{{ import.numeroFiche }}</td>
			</tr>
			<tr>
				<th>Libelle_civilite</th>
				<td>{{ import.libelleCivilite }}</td>
			</tr>
			<tr>
				<th>Propriete_vehicule</th>
				<td>{{ import.proprieteVehicule }}</td>
			</tr>
			<tr>
				<th>Nom</th>
				<td>{{ import.nom }}</td>
			</tr>
			<tr>
				<th>Prenom</th>
				<td>{{ import.prenom }}</td>
			</tr>
			<tr>
				<th>Num_nom_voie</th>
				<td>{{ import.numNomVoie }}</td>
			</tr>
			<tr>
				<th>Complement_adresse</th>
				<td>{{ import.complementAdresse }}</td>
			</tr>
			<tr>
				<th>Code_postal</th>
				<td>{{ import.codePostal }}</td>
			</tr>
			<tr>
				<th>Ville</th>
				<td>{{ import.ville }}</td>
			</tr>
			<tr>
				<th>Telephone_domicile</th>
				<td>{{ import.telephoneDomicile }}</td>
			</tr>
			<tr>
				<th>Telephone_portable</th>
				<td>{{ import.telephonePortable }}</td>
			</tr>
			<tr>
				<th>Telephone_job</th>
				<td>{{ import.telephoneJob }}</td>
			</tr>
			<tr>
				<th>Email</th>
				<td>{{ import.email }}</td>
			</tr>
			<tr>
				<th>Date_mise_en_circulation</th>
				<td>{{ import.dateMiseEnCirculation ? import.dateMiseEnCirculation|date('Y-m-d') : '' }}</td>
			</tr>
			<tr>
				<th>Date_achat</th>
				<td>{{ import.dateAchat ? import.dateAchat|date('Y-m-d') : '' }}</td>
			</tr>
			<tr>
				<th>Date_dernier_event</th>
				<td>{{ import.dateDernierEvent ? import.dateDernierEvent|date('Y-m-d') : '' }}</td>
			</tr>
			<tr>
				<th>Libelle_marque</th>
				<td>{{ import.libelleMarque }}</td>
			</tr>
			<tr>
				<th>Libelle_modele</th>
				<td>{{ import.libelleModele }}</td>
			</tr>
			<tr>
				<th>Version</th>
				<td>{{ import.version }}</td>
			</tr>
			<tr>
				<th>Vin</th>
				<td>{{ import.vin }}</td>
			</tr>
			<tr>
				<th>Immatriculation</th>
				<td>{{ import.immatriculation }}</td>
			</tr>
			<tr>
				<th>Type_prospect</th>
				<td>{{ import.typeProspect }}</td>
			</tr>
			<tr>
				<th>Kilometrage</th>
				<td>{{ import.kilometrage }}</td>
			</tr>
			<tr>
				<th>Libelle_energie</th>
				<td>{{ import.libelleEnergie }}</td>
			</tr>
			<tr>
				<th>Vendeur_vn</th>
				<td>{{ import.vendeurVn }}</td>
			</tr>
			<tr>
				<th>Vendeur_vo</th>
				<td>{{ import.vendeurVo }}</td>
			</tr>
			<tr>
				<th>Commentaire_facturation</th>
				<td>{{ import.commentaireFacturation }}</td>
			</tr>
			<tr>
				<th>Type_vn_vo</th>
				<td>{{ import.typeVnVo }}</td>
			</tr>
			<tr>
				<th>Num_dossier_vn_vo</th>
				<td>{{ import.numDossierVnVo }}</td>
			</tr>
			<tr>
				<th>Intermediaire_vente</th>
				<td>{{ import.intermediaireVente }}</td>
			</tr>
			<tr>
				<th>Date_evenement_veh</th>
				<td>{{ import.dateEvenementVeh ? import.dateEvenementVeh|date('Y-m-d') : '' }}</td>
			</tr>
			<tr>
				<th>Originine_evenement</th>
				<td>{{ import.originineEvenement }}</td>
			</tr>
		</tbody>
	</table>
{% endblock %}